// <auto-generated />
using System;
using Caterer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Caterer.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231206084822_Taxes")]
    partial class Taxes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Caterer.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Caterer.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CurrentStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MaximumStockDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MinimumStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalesPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warehouse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Caterer.Models.Restaurant", b =>
                {
                    b.Property<int>("ResturantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResturantId"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AutoRejectWaitTime")
                        .HasColumnType("int");

                    b.Property<int?>("AverageOrderPrepareTimeInMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("CanAutoAccept")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAutoReject")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeliver")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDineIn")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDispalyAllergensOnMenu")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEnableCostBasedOnRange")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEnableCoupons")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEnableCustomDeliveyCost")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEnableDrivers")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEnableExpenses")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEnableKitchenDisplaySystem")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEnableOrderAfterWorkingTimeOfTheStore")
                        .HasColumnType("bit");

                    b.Property<bool>("CanFreeDeliver")
                        .HasColumnType("bit");

                    b.Property<bool>("CanPickup")
                        .HasColumnType("bit");

                    b.Property<bool>("CanPreorder")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSelfDelivery")
                        .HasColumnType("bit");

                    b.Property<bool>("CanShowAllLanguages")
                        .HasColumnType("bit");

                    b.Property<bool>("CanShowDateTimePickerEvenIfStoreIsOpen")
                        .HasColumnType("bit");

                    b.Property<bool>("CanShowGoogleTranslate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanShowTax")
                        .HasColumnType("bit");

                    b.Property<int?>("CardPayoutdays")
                        .HasColumnType("int");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultTaxValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeliveryPreparationTime")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisableCOD")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableCardpayment")
                        .HasColumnType("bit");

                    b.Property<bool>("DisablePayNow")
                        .HasColumnType("bit");

                    b.Property<bool>("Disableordering")
                        .HasColumnType("bit");

                    b.Property<bool>("DoConversion")
                        .HasColumnType("bit");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fee")
                        .HasColumnType("float");

                    b.Property<string>("FifthRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FourthRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FreeDeliveryCost")
                        .HasColumnType("int");

                    b.Property<bool>("Friday")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FridayEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FridayStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Impressum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("KitchenThermalPrinterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainThermalPrinterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Minimum")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Minutes")
                        .HasColumnType("int");

                    b.Property<bool>("Monday")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MondayEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MondayStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PayNowFee")
                        .HasColumnType("float");

                    b.Property<int?>("PayNowPayOutDays")
                        .HasColumnType("int");

                    b.Property<int?>("PayNowServiceTax")
                        .HasColumnType("int");

                    b.Property<double>("PayNowStaticFee")
                        .HasColumnType("float");

                    b.Property<string>("PriceForFifthRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceForFirstRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceForFourthRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceForSecondRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceForThirdRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintA4StandardOrderWhen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintNodeApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintOnKitchenThermalPrinterWhen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintOnMainThermalPrinterWhen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QRPaymentWaitTime")
                        .HasColumnType("int");

                    b.Property<int>("ResId")
                        .HasColumnType("int");

                    b.Property<string>("RestaurantBankAccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantBankHolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantBankShortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Saturday")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SaturdayEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SaturdayStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondKitchenThermalPrinterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondMainPrinterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectYoutMenuTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceTax")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceTaxDineIn")
                        .HasColumnType("int");

                    b.Property<string>("StandardPrinterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StaticFee")
                        .HasColumnType("float");

                    b.Property<double>("StripeFee")
                        .HasColumnType("float");

                    b.Property<int?>("StripeServiceTax")
                        .HasColumnType("int");

                    b.Property<double>("StripeStaticFee")
                        .HasColumnType("float");

                    b.Property<bool>("Sunday")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SundayEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SundayStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TakeawayMin")
                        .HasColumnType("int");

                    b.Property<string>("ThirdRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Thursday")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ThursdayEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThursdayStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeFormatForClosingTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeFormatForOrders")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeSlotSeparatedInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleOfImpressum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TuesdayEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TuesdayStart")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WebhookCalledApprovedBySystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebhookCalledApprovedByvendor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("WednesdayEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WednesdayStart")
                        .HasColumnType("datetime2");

                    b.HasKey("ResturantId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("Caterer.Models.Tax", b =>
                {
                    b.Property<int>("TaxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxId"), 1L, 1);

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TaxNo")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("decimal");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TaxId");

                    b.ToTable("Tax");
                });

            modelBuilder.Entity("Caterer.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Caterer.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
